# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DStmDjNBL_wDWCGTshslOCQLPCv3Lrc7
"""

# accept two lists from the user and displayy their join
First_list =[]
print("Enter the objects for list ")
for i in range(5):
    value=int(input("Enter Any Numbers \n"))
    First_list.append(value)
Second_list =[]
print("Enter the objects for list 2 ")
for i in range(5):
    value2=int(input("Enter The numbers \n"))
    Second_list.append(value2)
list = First_list+Second_list
print(list)